const constants = {
    messageLengthStandards: {
        whole: {
            lat: 160,
            ru: 70,
        },
        partial: {
            lat: 153,
            ru: 67,
        },
    },
    TranslitTable:[
        {ru: 'a', lat: 'a'},
        {ru: 'А', lat: 'A'},
        {ru: 'б', lat: 'b'},
        {ru: 'Б', lat: 'B'},
        {ru: 'в', lat: 'v'},
        {ru: 'В', lat: 'V'},
        {ru: 'г', lat: 'g'},
        {ru: 'Г', lat: 'G'},
        {ru: 'д', lat: 'd'},
        {ru: 'Д', lat: 'D'},
        {ru: 'е', lat: 'e'},
        {ru: 'Е', lat: 'E'},
        {ru: 'ё', lat: 'yo'},
        {ru: 'Ё', lat: 'Yo'},
        {ru: 'ж', lat: 'zh'},
        {ru: 'Ж', lat: 'Zh'},
        {ru: 'з', lat: 'z'},
        {ru: 'З', lat: 'Z'},
        {ru: 'и', lat: 'i'},
        {ru: 'И', lat: 'I'},
        {ru: 'й', lat: 'y'},
        {ru: 'Й', lat: 'Y'},
        {ru: 'к', lat: 'k'},
        {ru: 'К', lat: 'K'},
        {ru: 'л', lat: 'l'},
        {ru: 'Л', lat: 'L'},
        {ru: 'м', lat: 'm'},
        {ru: 'М', lat: 'M'},
        {ru: 'н', lat: 'n'},
        {ru: 'Н', lat: 'N'},
        {ru: 'о', lat: 'o'},
        {ru: 'О', lat: 'O'},
        {ru: 'п', lat: 'p'},
        {ru: 'П', lat: 'P'},
        {ru: 'р', lat: 'r'},
        {ru: 'Р', lat: 'R'},
        {ru: 'с', lat: 's'},
        {ru: 'С', lat: 'S'},
        {ru: 'т', lat: 't'},
        {ru: 'Т', lat: 'T'},
        {ru: 'у', lat: 'u'},
        {ru: 'У', lat: 'U'},
        {ru: 'ф', lat: 'f'},
        {ru: 'Ф', lat: 'F'},
        {ru: 'х', lat: 'h'},
        {ru: 'Х', lat: 'H'},
        {ru: 'ц', lat: 'ts'},
        {ru: 'Ц', lat: 'Ts'},
        {ru: 'ч', lat: 'ch'},
        {ru: 'Ч', lat: 'Ch'},
        {ru: 'ш', lat: 'sh'},
        {ru: 'Ш', lat: 'Sh'},
        {ru: 'щ', lat: 'sch'},
        {ru: 'Щ', lat: 'Sch'},
        {ru: 'ъ', lat: '\''},
        {ru: 'Ъ', lat: '\''},
        {ru: 'ы', lat: 'i'},
        {ru: 'Ы', lat: 'I'},
        {ru: 'ь', lat: '\''},
        {ru: 'Ь', lat: '\''},
        {ru: 'э', lat: 'e'},
        {ru: 'Э', lat: 'E'},
        {ru: 'ю', lat: 'u'},
        {ru: 'Ю', lat: 'U'},
        {ru: 'я', lat: 'ya'},
        {ru: 'Я', lat: 'Ya'},
        {ru: '«', lat: '"'},
        {ru: '»', lat: '"'},
        {ru: '–', lat: '-'},
        {ru: '—', lat: '-'},
        {ru: '№', lat: '#'},
        {ru: '`', lat: '\''},
    ]
}

export default constants;
